plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

repositories { mavenCentral() }

loom {
    splitEnvironmentSourceSets()
    mods {
        'donut' {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}

sourceSets.test {
    compileClasspath += sourceSets.client.output + sourceSets.client.compileClasspath
    runtimeClasspath += sourceSets.client.output + sourceSets.client.runtimeClasspath
}

test { useJUnitPlatform() }

fabricApi {
    configureTests {
        createSourceSet = true
        modId = 'donut-gametest'
        enableGameTests = false
        enableClientGameTests = true
    }
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}

jar { from('LICENSE') { rename { "${it}_${project.base.archivesName.get()}" } } }
